config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout", sign_up: "sign-up"}
  root "welcome#index"

  resources :posts
  resources :quotes
 
  get "/random", to: "random_quotes#new", as: "new_random_quote"
  get "/d3_data", to: "random_quotes#d3_data", as: "d3_data" 
  

end

app/models/post.rb
class Post < ActiveRecord::Base
	has_attached_file :image, :styles => { large: "320x320>", thumb: "100x100>"}
	# , :default_url => "images/:styles/missing.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
	
	belongs_to :user
	validates :body,
		presence: true,
		length: { minimum: 20 }
end

app/models/quote.rb
class Quote < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts, dependent: :destroy
  has_many :quotes, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  def after_sign_in_path_for(resource)
    posts_path
  end

end

app/controllers/posts_controller.rb
require "json"
class PostsController < ApplicationController
	before_action :user_redirect
	skip_before_action :verify_authenticity_token

	def index
		@posts = Post.all
		@post = Post.new
		@user = User.find(current_user.id)
		@quote_api_key = Rails.application.secrets.quote_api_key
		@response = Unirest.post "https://andruxnet-random-famous-quotes.p.mashape.com/?cat=famous",
														  headers:{
														    "X-Mashape-Key" => @quote_api_key,
														    "Content-Type" => "application/x-www-form-urlencoded",
														    "Accept" => "application/json"
														  }
		data = @response.body
		@daily_quote = data["quote"]
		@author = data["author"]

		# counting words section
		thoughts = []
		@user.posts.each do |p| 
			thoughts.push(p.body.split)
		end
		
		@thoughts_flatten = thoughts.flatten 
		@thoughts_hash = counted_words(@thoughts_flatten) #function to count flattened words
		# Changing above hash to this format: [{word => "df", count => 1}, {word => "s", count => 4}]
		@thoughts_arry = change_counted_word_format(@thoughts_hash) 
		@thoughts_json = @thoughts_arry.to_json #tansfering data to json
	end

	def create
		@user = User.find(current_user.id)
		@posts = Post.all
		@post = Post.new(post_params)
		if @post.save
			redirect_to "/posts"
		else
			render "index"
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to "/posts"
	end

	private
		def post_params
			params.require(:post).permit(:body, :user_id, :image)
		end

		def user_redirect
			if !current_user
				flash[:error] = "You must be logged in to access this page"
				redirect_to "/"
			end
		end

		def counted_words(arry)
			count_words = {}
			arry.each do |word| 
				if count_words.has_key?(word)
					value = count_words.fetch(word)
					count_words[word] = value + 1
				else
					count_words[word] = 1
				end
			end
			return count_words
		end

		def change_counted_word_format(hash)
			arry = []
			hash.each do |k, v|
				arry << {"word" => k, "count" => v}
			end
			return arry
		end
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
	def index
		@user = User.find(current_user.id)
		@quotes = Quote.all
	end

	def create
		@quote = Quote.create(quote_params)
		respond_to do |format|
      		format.js { render :create }
   	 end
	end

	def destroy
		@quote = Quote.find(params[:id])
		@quote.destroy
		redirect_to "/quotes"
	end

	private
		def quote_params
			params.permit(:quotes, :author, :user_id)
		end

end

app/controllers/random_quotes_controller.rb
class RandomQuotesController < ApplicationController

	def new
		@quote_api_key = Rails.application.secrets.quote_api_key
		@response = Unirest.post "https://andruxnet-random-famous-quotes.p.mashape.com/?cat=famous",
														  headers:{
														    "X-Mashape-Key" => @quote_api_key,
														    "Content-Type" => "application/x-www-form-urlencoded",
														    "Accept" => "application/json"
														  }
		data = @response.body
		@daily_quote = data["quote"]
		@author = data["author"]
		
		respond_to do |format|
			format.js
		end
	end

	# calling in JSON data as url 
	def d3_data
		@posts = Post.all
		@user = User.find(current_user.id)

		# counting words section
		thoughts = []
		@user.posts.each do |p| 
			thoughts.push(p.body.split)
		end

		@thoughts_flatten = thoughts.flatten 
		@thoughts_hash = counted_words(@thoughts_flatten) #function to count flattened words
		@thoughts_arry = change_counted_word_format(@thoughts_hash)  #changing hash format
		@thoughts_json = @thoughts_arry.to_json #tansfering data to json
		render(json: @thoughts_json)
	end

	private
	
	def counted_words(arry)
		count_words = {}
		arry.each do |word| 
			if count_words.has_key?(word)
				value = count_words.fetch(word)
				count_words[word] = value + 1
			else
				count_words[word] = 1
			end
		end
		return count_words
	end

	def change_counted_word_format(hash)
		arry = []
		hash.each do |k, v|
			arry << {"word" => k, "count" => v}
		end
		return arry
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :user_redirect_welcome

	def index
		@posts = Post.all
	end

	private 
		def user_redirect_welcome
			if current_user
				redirect_to "/posts"
			end
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper

end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/helpers/random_quotes_helper.rb
module RandomQuotesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HappyThoughts</title>
  <script src="https://d3js.org/d3.v4.min.js"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<!-- if the user is not signed in  -->
<% if !user_signed_in? %>

			<nav>
				<a href="/" id="logo">
					<span id="logo">
						<span>happy</span>
						<span id="black">thoughts</span>
					</span>
				</a>

				<ul class="topnav" id="myTopnav">
				  <li class="icon">
				    <a href="javascript:void(0);"  onclick="myFunction()">☰</a>
				  </li>
				   <li class="iconX">
				    <a href="javascript:void(0);"  onclick="myFunction()">X</a>
				  </li>
				  <li><a href="/users/login">Log In</a></li>
				  <li><a href="/users/sign-up">Sign Up</a></li>
				  <li><a href="/">Home</a></li>
				</ul>

			</nav>
<% end %> 


<!-- if the user is signed in -->
<% if user_signed_in? %>
	<nav>	

			<a href="/posts" id="logo">
				<span id="logo">
					<span>happy</span>
					<span id="black">thoughts</span>
				</span>
			</a>
	

				<ul class="topnav" id="myTopnav">
				  <li class="icon">
				    <a href="javascript:void(0);"  onclick="myFunction()">☰</a>
				  </li>
				   <li class="iconX">
				    <a href="javascript:void(0);"  onclick="myFunction()">X</a>
				  </li>
				  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %> </li>
				  <li><a href="/users/edit">Settings</a></li>
				  <li><a href="/quotes">Favorites</a></li>
				  <li><a href="/posts">Profile</a></li>
				  
				</ul>
	</nav>
<% end %>	

<%= flash[:error] if flash[:error] %>
<!-- Flash message when login fails or any type of flash messages for each key & values -->
<!-- Flash[:alert] & flash[:notice] -->

<!-- <% flash.each do |key, value| %> -->
    <!-- # <div class="flash <%= key %>"><%= value %></div> -->
 <!-- <% end %> -->

 <%= flash[:alert] if flash[:alert] %>


<%= yield %>

</body>
<script type="text/javascript" src="menu.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.0/jquery.min.js"></script> 
</html>

app/views/posts/_form.html.erb
<%= form_for @post, html: { multipart: true } do |f| %>
	<div id="error_messages">
		<% if @post.errors.any? %>
			<h3>
				<%= pluralize(@post.errors.count, "error") %>
				Prohibited posts to be posted.
			</h3>
			<ul>
				<% @post.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		<% end %>
	</div>

	

		<%= f.text_area :body, placeholder:'Today I was happy when   ...', class:'u-full-width'%>
		
				<%= f.file_field :image%>
				<%= f.submit 'happy', id:'happy_b' %>
		<%= f.hidden_field :user_id, :value => current_user.id %>
	

<% end %>

app/views/posts/index.html.erb
<!-- ///////////QUOTES VISUALIZATION //////////////-->
<!-- <h8><%= @thoughts_json %></h8> -->

<!-- JS script in  -->
<!-- <%= javascript_tag do %>
  alert("My example alert box.");
<% end %> -->

<div class="container">
    <div id="home" class="row"> 
		<!-- /////// DISPLAY A QUOTE /////////////-->
   		<div id="quote" class="twelve columns">	
			<span id="comilla_1"> “ </span>
			<span id="comilla_2"> ” </span>
			<h5 id="daily_quote"> <%= @daily_quote %> </h5>
			<h6 id="quote_author"> - <%= @author %></h6>
		</div>


<div id="buttons_q" class="twelve columns">
	
			<div id="saving_quote">
				<%= link_to "Save", quotes_path(:quotes => @daily_quote, :author => @author, :user_id => current_user.id), remote: true, :method => :post %>
			</div> 

			<div id="quote_generator">
				<%= link_to "Quote", new_random_quote_path, remote: true %>
			</div>

</div>



			<!-- /////// CONTAINER POSTS  /////////////-->
			<div  id="post_container" class="twelve columns">
				<!-- /////// CREATE A POST /////////////-->
				<div id="tho" class="six columns">
					<%= render "form" %>



			<div id="visual_container" class="twelve columns">
				<div id="chart">
				</div>
				<div id="legend">
				</div>
			</div>

	     	</div> 

			<!-- /////// DISPLAY ALL YOUR POSTS /////////////-->
			<div  class="six columns ">
				<% if @posts != nil %>
						<% @user.posts.reverse.each do |p| %>
							<div id="happy_post" class="twelve columns">
								<% if p.user_id == current_user.id %>
									<div id="close"> <%= link_to " X ", post_path(p.id), :method => :delete, 
												:data => {confirm: "Do you wish to delete your happy moment?"} %>
									</div>
									<div id="time">
										<%= p.created_at.strftime("%D") %>
									</div>
									
									<div id="name">
									-	<%= p.user.username %>
									</div>
									<p><%= p.body %></p>
									<%= image_tag p.image.url(:large) unless p.image_file_name.nil? %>
								<% end %>
							 </div> 
						<% end %>			
				<% end %>
			</div> 
		</div>



	</div>
</div>	
<!-- creating a variable for javascript -->
<script type="text/javascript"> 
	var my_data = "<%= j @thoughts_json %>"
</script>

app/views/quotes/create.js.erb
var saved_quote = document.getElementById("saving_quote")
saved_quote.innerHTML = "<a id='saved'> Saved !! </a>";

app/views/quotes/index.html.erb
<div class="container">
     <div id="home" class="row"> 
		<% @user.quotes.each do |q| %>
			 <div id="quote" class="twelve columns">		
			 	<div id="close">				
					<%= link_to "X", quote_path(:id => q.id), 
							:method => :delete, 
							:data => { confirm: "Do you wish to delete your quote?" } %>
				</div>	
				<span id="comilla_1"> “ </span>
				<span id="comilla_2"> ” </span>
				<h5><%= q.quotes %> </h5>
				<h6> - <%= q.author %> </h6>

			 </div>  
		<% end %>
	</div>
</div>


             
        

app/views/random_quotes/new.js.erb
var random_quote = document.getElementById("quote_generator");
random_quote.innerHTML = "<a data-remote='true' href='/random'>Quote</a>"

var saved_quote = document.getElementById("saving_quote");
var link = "<%= j link_to('Save', quotes_path(:quotes => @daily_quote, :author => @author, :user_id => current_user.id), remote: true, :method => :post) %>";
saved_quote.innerHTML = link;

var daily_quote = document.getElementById("daily_quote");
daily_quote.innerHTML = "<%= @daily_quote %>"

var quote_author = document.getElementById("quote_author");
quote_author.innerHTML = "- <%= @author %>"

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Happy Thoughts</title>
		<link rel="stylesheet" type="text/css" href="/assets/stylesheet/welcome.scss">
		<link rel="stylesheet" type="text/css" href="/assets/stylesheet/reset.css">
		<meta name="viewport" content="width=device-width, initial-scale=1">
	</head>
	<body>
		  <div class="container">
		      <div id="home" class="row">     
		           <div class="twelve columns">
		              <img src="images/cloud.svg">
		              <h5 >Welcome to Happy Thoughts</h5>
		              <p>A daily journal to keep you motivated.</p>

		       		<div class="four columns" id="invisible">s</div>
		            <div id="front_links" class="four columns">
			             <a id="f_link_1" href="/users/sign-up" >
			              	 <button id="primary">Sign Up </button>
			             </a>

			             <a id="f_link_2" href="/users/login" > 
			              	<button>Log in</button>
			             </a>
		            </div>
		          </div>  


			    <div id="info" class="twelve columns">

			         <div id="explanation" class="twelve columns">


					        <div id="what" class="six columns">
				        		<h3> What is this all about ? </h3>
					        </div>


						    <div id="what_p" class="six columns">
						    			
								    		We can't control what happens in a day, but you can control whether it is a bad or good day.
								    		<br>	<br>

									    	The human mind can go from positive to negative easily, but going from negative to positive is a lot harder!
											<br>	<br>

									    	Happy Thoughts helps you break that negative hold and reminds you that there is a ray of sunlight during a cloudy day!
											<br>	<br>
									    	Please watch the video below, "Getting stuck in the negatives (and how to get unstuck)" by Alison Ledgerwood. This video explains the value of Happy Thoughts and where it came from
									    	<br>	<br>
							</div>
			  	 	 </div>



				    <div id="explanation" class="twelve columns">
				    	<div class="videoWrapper">
				    		<%= video_tag "vid001.mp4", :size => "520x440", :controls => true %>
						</div>
					 </div>

			    	
					 <div id="explanation" class="twelve columns">
		      				
		      				<div id="what" class="six columns">
				        		<h3> How this works ? </h3>
					        </div>

						    <div id="what_p" class="six columns">
						    			
								    	<ol>
								    		<li>Post at least 3 things that is positive or makes you happy during that day!</li>
								    		<li>Come back and remind yourself of those good things anytime!</li>
								    		<li>Check out what others are writing and get inspired!</li>
								    	</ol>
								  
							</div>
					</div>

						 <div id="explanation" class="twelve columns">
		      					
		
		      				<div id="what" class="six columns">
				        	  <h3>Everyone's Happy Thoughts</h3>
					        </div>

							   
					        <div class="six columns">
							          <% @posts.reverse.each do |p| %>

							          <div id="happy_post" class="twelve columns">
								         
								         <div id="time">
								            <%= p.created_at.strftime("%D") %> - <%= p.user.email %>
								    	</div>

								            <%= image_tag p.image.url(:thumb) unless p.image_file_name.nil? %>
								            <br>
								          <p> <%= p.body %></p>
								        
							        </div>
							  <% end %>
						</div>

						</div>

					</div>
			  
		     </div>

	</body>
</html>